package bg.sofia.uni.fmi.ai.bayes.classifier;

public enum FeatureName {
	HANDICAPPED_INFANTS, WATER_PROJECT_COST_SHARING, ADOPTION_BUDGET_RESOLUTION, PHYSICIAN_FEE_FREEZE, EL_SALVADOR_AID,
	RELIGIOUS_GROUPS_IN_SCHOOLS, ANTI_SATELLITE_TEST_BAN, AID_NICARAGUAN_CONTRAS, MX_MISSILE, IMMIGRATION,
	SYNFUELS_CORPORATION_CUTBACK, EDUCATION_SPENDING, SUPERFUND_RIGHT_TO_SUE, CRIME, DUTY_FREE_EXPORTS,
	EXPORT_ADMINISTRATION_ACT_SOUTH_AFRICA
}
